### ISSUE TITLE
Trying to install package.json 

### ISSUE THREAD

**Issue by andrewjtimmons** [DevProgress/debate-bingo#20]
Hi!  I would love to pull some issues and contrubte.  I am having a bit of trouble getting up and running with this instructions.  Did you get this error and get past it?  I googled around a bit but didnt see anything that applied

When I do

```
sudo npm install -g
```

I get and error that seems to be referring to the line in this file
https://github.com/DevProgress/debate-bingo/blob/master/src/debate-bingo.js#L7

```
> debate-bingo@1.0.0 postinstall /usr/local/lib/node_modules/debate-bingo
> npm run webpack-prod


> debate-bingo@1.0.0 webpack-prod /usr/local/lib/node_modules/debate-bingo
> webpack -p

Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.13.2
Time: 77ms
             Asset       Size  Chunks             Chunk Names
        index.html  487 bytes          [emitted]  
images/hillary.png     5.1 kB          [emitted]  
  images/mixed.png    3.61 kB          [emitted]  
  images/trump.png    5.25 kB          [emitted]  
  data/hillary.dat  723 bytes          [emitted]  
 data/hillary.json     1.5 kB          [emitted]  
   data/mixed.json    1.53 kB          [emitted]  
    data/trump.dat  810 bytes          [emitted]  
   data/trump.json    1.55 kB          [emitted]  
    + 1 hidden modules

ERROR in ./src/debate-bingo.js
Module parse failed: /usr/local/lib/node_modules/debate-bingo/src/debate-bingo.js Unexpected token (7:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (7:4)
    at Parser.pp$4.raise (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/usr/local/lib/node_modules/debate-bingo/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/usr/local/lib/node_modules/debate-bingo/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/usr/local/lib/node_modules/debate-bingo/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/debate-bingo/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/usr/local/lib/node_modules/debate-bingo/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /usr/local/lib/node_modules/debate-bingo/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/usr/local/lib/node_modules/debate-bingo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /usr/local/lib/node_modules/debate-bingo/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**Comment by dglazkov** [comment]
Try `npm install` in the project dir. Lemme update the docs real quick (edited my spurious questions out).
